=== prestoprime/p4/p4core/conf/xsd/conf/tools.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns="http://www.prestoprime.eu/model/2012/tools" 
           elementFormDefault="qualified" 
           attributeFormDefault="unqualified" 
           targetNamespace="http://www.prestoprime.eu/model/2012/tools">
<xs:element name="tools">		
   <xs:complexType>
      <xs:sequence>
         <xs:element type="tool" name="tool" maxOccurs="unbounded"/>						    
	  </xs:sequence>
   </xs:complexType>
</xs:element>
<xs:complexType name="tool">
   <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="executable" name="executable" maxOccurs="unbounded"/>
      <xs:element type="dynlib" name="dynlib" minOccurs="0" maxOccurs="unbounded"/>
   </xs:sequence>
</xs:complexType>
<xs:complexType name="executable">
   <xs:simpleContent>
      <xs:extension base="xs:string">
         <xs:attribute name="os.name" use="required">
            <xs:simpleType>
	           <xs:restriction base="xs:string">
		          <xs:enumeration value="Linux"/>
		          <xs:enumeration value="Windows"/>
		          <xs:enumeration value="MacOS"/>
	           </xs:restriction>
	        </xs:simpleType>
	     </xs:attribute>
	  </xs:extension>
   </xs:simpleContent>       
</xs:complexType>
<xs:complexType name="dynlib">
   <xs:simpleContent>
      <xs:extension base="xs:string">
         <xs:attribute name="os.name" use="required">
            <xs:simpleType>
	           <xs:restriction base="xs:string">
		          <xs:enumeration value="Linux"/>
		          <xs:enumeration value="Windows"/>
		          <xs:enumeration value="MacOS"/>
	           </xs:restriction>
	        </xs:simpleType>
	     </xs:attribute>
	  </xs:extension>
   </xs:simpleContent>       
</xs:complexType>
</xs:schema>

=== prestoprime/p4/p4core/conf/tools.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tools xmlns="http://www.prestoprime.eu/model/2012/tools" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.prestoprime.eu/model/2012/tools tools.xsd">
  <tool>
    <name>FFMPEG</name>
    <executable os.name="Linux">/usr/bin/ffmpeg</executable>
  </tool>
  <tool>
    <name>FFMBC</name>
    <executable os.name="Linux">/opt/p4/tools/bin/ffmbc</executable>
  </tool>
  <tool>
    <name>FFPROBE</name>
    <executable os.name="Linux">/usr/bin/ffprobe</executable>
  </tool>
  <tool>
    <name>FFMPEG2THEORA</name>
    <executable os.name="Linux">/usr/bin/ffmpeg2theora</executable>
  </tool>
  <tool>
    <name>D10SUMCHECKER</name>
    <executable os.name="Linux">/opt/p4/tools/bin/d10sumchecker</executable>
    <dynlib os.name="Linux">/opt/p4/tools/bin/libd10sumchecker.so</dynlib>
  </tool>
  <tool>
    <name>XSLTPROC</name>
    <executable os.name="Linux">/usr/bin/xsltproc</executable>
  </tool>
  <tool>
    <name>DOT</name>
    <executable os.name="Linux">/usr/bin/dot</executable> 
  </tool>
</tools>
